/* eslint-disable import/prefer-default-export */

export const includes = [
  'brainfuck',
  'clojure',
  'cmake',
  'cobol',
  'coffeescript',
  'commonlisp',
  'crystal',
  'css',
  'd',
  'dart',
  'diff',
  'django',
  'dockerfile',
  'elm',
  'erlang',
  'fortran',
  'go',
  'groovy',
  'haskell',
  'haxe',
  'htmlmixed',
  'http',
  'javascript',
  'jinja2',
  'jsx',
  'julia',
  'lua',
  'markdown',
  'mathematica',
  'nginx',
  'pascal',
  'perl',
  'php',
  'powershell',
  'properties',
  'protobuf',
  'pug',
  'puppet',
  'python',
  'r',
  'rst',
  'ruby',
  'rust',
  'sass',
  'scheme',
  'shell',
  'smalltalk',
  'smarty',
  'solr',
  'sparql',
  'spreadsheet',
  'sql',
  'stylus',
  'swift',
  'toml',
  'twig',
  'vb',
  'vbscript',
  'vue',
  'xml',
  'yaml-frontmatter',
  'yaml',
];

export const mimeMap = {
  C: 'text/x-csrc',
  'C#': 'text/x-csharp',
  'C++': 'text/x-c++src',
  CMake: 'text/x-cmake',
  COBOL: 'text/x-cobol',
  'Common Lisp': 'text/x-common-lisp',
  CPython: 'text/x-cython',
  CSS: 'text/css',
  Dart: 'application/dart',
  Dockerfile: 'text/x-dockerfile',
  Elm: 'text/x-elm',
  Erlang: 'text/x-erlang',
  Fortran: 'text/x-fortran',
  Golang: 'text/x-go',
  GraphQL: 'graphql',
  Groovy: 'text/x-groovy',
  Haskell: 'text/x-haskell',
  HiveSQL: 'text/x-hive',
  HTML: 'text/html',
  Java: 'text/x-java',
  Javascript: 'text/javascript',
  JSON: 'application/json',
  LESS: 'text/x-less',
  Markdown: 'gfm',
  MSSQL: 'text/x-mssql',
  MySQL: 'text/x-mysql',
  'Objective-C': 'text/x-objectivec',
  Pascal: 'text/x-pascale',
  Perl: 'text/x-perl',
  PgSQL: 'text/x-pgsql',
  PHP: 'text/x-php',
  'PHP+HTML': 'application/x-httpd-php',
  PowerShell: 'application/x-powershell',
  Python: 'text/x-python',
  reStructuredText: 'text/x-rst',
  Ruby: 'text/x-ruby',
  Rust: 'text/x-rustsrc',
  Scala: 'text/x-scala',
  Schema: 'text/x-schema',
  SCSS: 'text/x-scss',
  Shellscript: 'text/x-sh',
  SQL: 'text/x-sql',
  Swift: 'text/x-swift',
  TOML: 'text/x-toml',
  Typescript: 'text/typescript',
  'VB.NET': 'text/x-vb',
  VueJS: 'text/x-vue',
  XML: 'application/xml',
  YAML: 'text/x-yaml',
};
