name: Dockite CI

on:
  push:
    branches: [ develop ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'chore(release): publish packages')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: yarn global add lerna
    - run: echo "::add-path::$(yarn global bin)"

    - run: lerna bootstrap
    - run: lerna run build --scope @dockite/types
    - run: lerna run build --scope @dockite/manager
    - run: lerna run build --ignore @dockite/admin --ignore @dockite/core --ignore @dockite/field-* --parallel
    - run: lerna run build --scope @dockite/field-* --parallel
    - run: lerna run build --scope @dockite/core --scope @dockite/admin --parallel

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
        registry-url: 'https://registry.npmjs.org'
        scope: '@octocat'
        always-auth: true

    - run: yarn global add lerna
    - run: echo "::add-path::$(yarn global bin)"

    - run: lerna bootstrap
    - run: lerna run build --scope @dockite/types
    - run: lerna run build --scope @dockite/manager
    - run: lerna run build --ignore @dockite/admin --ignore @dockite/core --ignore @dockite/field-* --parallel
    - run: lerna run build --scope @dockite/field-* --parallel
    - run: lerna run build --scope @dockite/core --scope @dockite/admin --parallel

    - run: git config --local user.email "action@github.com"
    - run: git config --local user.name "GitHub Action"

    - run: 'lerna version -m "chore(release): publish packages" --conventional-commits --conventional-prerelease --no-push --yes'
    - run: yarn config set access public
    - run: npm config set access public
    - run: |
        npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
        lerna publish from-git --yes
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: develop
        github_token: ${{ secrets.GH_PAT }}
        tags: true
