name: Dockite CI

on:
 pull_request:
    branches: [ develop, master ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'chore(release): publish packages')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: yarn global add lerna
    - run: echo "::add-path::$(yarn global bin)"

    - run: lerna bootstrap
    - run: lerna run build --scope @dockite/types
    - run: lerna run build --scope @dockite/manager
    - run: lerna run build --ignore @dockite/admin --ignore @dockite/core --ignore @dockite/field-* --parallel
    - run: lerna run build --scope @dockite/field-* --parallel
    - run: lerna run build --scope @dockite/core --scope @dockite/admin --parallel
